# ARTIFICIAL NEURAL NETWORKS - CHURN MODELLING

In [19]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.9.2'

In [6]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
Y = dataset.iloc[:,-1].values

In [7]:
print(Y)

[1 0 1 ... 1 1 0]


In [8]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])


In [10]:
#One Hot Encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [12]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
#Intializing the ANN
ann = tf.keras.models.Sequential()
#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
#Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
#Adding the output. layer
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))

In [14]:
#compiling
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy', metrics = ['accuracy']) #adam - adaptive moment estimation
#training
ann.fit(X_train,y_train,batch_size = 32,epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5222 - accuracy: 0.7884
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4640 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4487 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4390 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4329 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4286 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4250 - accuracy: 0.7972
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4217 - accuracy: 0.8102
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4185 - accuracy: 0.8155
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4156 - accura

In [15]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 109ms/step
[[False]]


In [16]:
#predicting the test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred,y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [17]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1506   89]
 [ 193  212]]


In [18]:
accuracy_score(y_test,y_pred)

0.859